// <auto-generated />
namespace BMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class solved1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(solved1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508221311047_solved1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
