// <auto-generated />
namespace BMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Recreate_bd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recreate_bd));
        
        string IMigrationMetadata.Id
        {
            get { return "201508211604328_Recreate_bd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
