// <auto-generated />
namespace BMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class solvequation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(solvequation));
        
        string IMigrationMetadata.Id
        {
            get { return "201508230908332_solvequation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
